// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KorakPoKorak.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814203527_AddLessonExerciseContentBlocks")]
    partial class AddLessonExerciseContentBlocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ActivityProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Context")
                        .HasColumnType("integer");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId", "UnitType", "UnitId")
                        .IsUnique();

                    b.ToTable("ActivityProgresses");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ChildProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ChildProfiles");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LessonId");

                    b.HasIndex("MediaAssetId");

                    b.ToTable("ContentBlocks", t =>
                        {
                            t.HasCheckConstraint("CK_ContentBlocks_OneOwner", "(\"LessonId\" IS NOT NULL AND \"ExerciseId\" IS NULL) OR (\"LessonId\" IS NULL AND \"ExerciseId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.HasIndex("ChildProfileId", "WorkshopId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrintable")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "System administrator with full access to all features.",
                            RoleName = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mentor who guides and supports children on the platform.",
                            RoleName = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Child user of the platform.",
                            RoleName = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Parent who manages their children's profiles and activities.",
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("AgeMax")
                        .HasColumnType("integer");

                    b.Property<int>("AgeMin")
                        .HasColumnType("integer");

                    b.Property<int>("ComplexityLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("WorkshopExercises", b =>
                {
                    b.Property<int>("ExercisesId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopsId")
                        .HasColumnType("integer");

                    b.HasKey("ExercisesId", "WorkshopsId");

                    b.HasIndex("WorkshopsId");

                    b.ToTable("WorkshopExercises");
                });

            modelBuilder.Entity("WorkshopLessons", b =>
                {
                    b.Property<int>("LessonsId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopsId")
                        .HasColumnType("integer");

                    b.HasKey("LessonsId", "WorkshopsId");

                    b.HasIndex("WorkshopsId");

                    b.ToTable("WorkshopLessons");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ActivityProgress", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("ActivityProgresses")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ChildProfile", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ContentBlock", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Exercise", "Exercise")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorakPoKorak.Domain.Entities.Lesson", "Lesson")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorakPoKorak.Domain.Entities.MediaAsset", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Lesson");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Enrollments")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.Workshop", "Workshop")
                        .WithMany("Enrollments")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.User", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Workshop", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("WorkshopExercises", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.Workshop", null)
                        .WithMany()
                        .HasForeignKey("WorkshopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkshopLessons", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.Workshop", null)
                        .WithMany()
                        .HasForeignKey("WorkshopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ChildProfile", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Enrollment", b =>
                {
                    b.Navigation("ActivityProgresses");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Workshop", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
