// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KorakPoKorak.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ActivityProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Context")
                        .HasColumnType("integer");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId", "UnitType", "UnitId")
                        .IsUnique();

                    b.ToTable("ActivityProgresses");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.BadgeAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BadgeTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("ChildProfileId")
                        .HasColumnType("integer");

                    b.Property<int?>("EnrollmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeTemplateId");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("WorkshopId");

                    b.HasIndex("ChildProfileId", "BadgeTemplateId")
                        .IsUnique()
                        .HasDatabaseName("IX_BadgeAwards_OncePerChild")
                        .HasFilter("\"Scope\" = 0");

                    b.HasIndex("ChildProfileId", "BadgeTemplateId", "WorkshopId")
                        .IsUnique()
                        .HasDatabaseName("IX_BadgeAwards_OncePerChildWorkshop")
                        .HasFilter("\"Scope\" = 1 AND \"WorkshopId\" IS NOT NULL");

                    b.ToTable("BadgeAwards");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.BadgeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BadgeTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Code = "WORKSHOP_MASTER",
                            Description = "Dodeli se za svaku uspešno završenu radionicu.",
                            IconUrl = "/badges/workshop_master.svg",
                            Name = "Majstor radionice",
                            Scope = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Code = "FIRST_WORKSHOP",
                            Description = "Dodeli se za prvu uspešno završenu radionicu.",
                            IconUrl = "/badges/first_workshop.svg",
                            Name = "Prvi korak",
                            Scope = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Code = "PERSISTENT",
                            Description = "Dodeli se za drugu uspešno završenu radionicu.",
                            IconUrl = "/badges/persistent.svg",
                            Name = "Upornost",
                            Scope = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Code = "THREE_WORKSHOPS",
                            Description = "Dodeli se za treću uspešno završenu radionicu.",
                            IconUrl = "/badges/three_workshops.svg",
                            Name = "Iskusni istraživač",
                            Scope = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Code = "CURIOUS_MIND",
                            Description = "Dodeli se za četvrtu uspešno završenu radionicu.",
                            IconUrl = "/badges/curious_mind.svg",
                            Name = "Radoznali um",
                            Scope = 0
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Code = "FIVE_WORKSHOPS",
                            Description = "Dodeli se za petu uspešno završenu radionicu.",
                            IconUrl = "/badges/five_workshops.svg",
                            Name = "Veliki istraživač",
                            Scope = 0
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Code = "GREAT_PROGRESS",
                            Description = "Dodeli se za šestu uspešno završenu radionicu.",
                            IconUrl = "/badges/great_progress.svg",
                            Name = "Veliki napredak",
                            Scope = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Code = "DEDICATED",
                            Description = "Dodeli se za sedmu uspešno završenu radionicu.",
                            IconUrl = "/badges/dedicated.svg",
                            Name = "Posvećeni učenik",
                            Scope = 0
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Code = "EXPLORER",
                            Description = "Dodeli se za osmu uspešno završenu radionicu.",
                            IconUrl = "/badges/explorer.svg",
                            Name = "Istraživač",
                            Scope = 0
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Code = "TEN_WORKSHOPS",
                            Description = "Dodeli se za desetu uspešno završenu radionicu.",
                            IconUrl = "/badges/ten_workshops.svg",
                            Name = "Avanturista",
                            Scope = 0
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Code = "SUPER_LEARNER",
                            Description = "Dodeli se za petnaestu uspešno završenu radionicu.",
                            IconUrl = "/badges/super_learner.svg",
                            Name = "Super učenik",
                            Scope = 0
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            Code = "CHAMPION",
                            Description = "Dodeli se za dvadesetu uspešno završenu radionicu.",
                            IconUrl = "/badges/champion.svg",
                            Name = "Šampion",
                            Scope = 0
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            Code = "KNOWLEDGE_STAR",
                            Description = "Dodeli se za prvu završenu radionicu srednje težine.",
                            IconUrl = "/badges/knowledge_star.svg",
                            Name = "Zvezda znanja",
                            Scope = 0
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            Code = "BRAVE_STEP",
                            Description = "Dodeli se za prvu završenu naprednu radionicu.",
                            IconUrl = "/badges/brave_step.svg",
                            Name = "Hrabri korak",
                            Scope = 0
                        },
                        new
                        {
                            Id = 15,
                            Category = 0,
                            Code = "CREATIVE_STAR",
                            Description = "Dodeli se za prvu završenu radionicu sa više vrsta aktivnosti.",
                            IconUrl = "/badges/creative_star.svg",
                            Name = "Kreativna zvezda",
                            Scope = 0
                        });
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.CertificateAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("CertificateTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("CertificateTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ChildFullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ChildProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MentorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("WorkshopId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkshopTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNumber")
                        .IsUnique();

                    b.HasIndex("CertificateTemplateId");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.HasIndex("WorkshopId");

                    b.ToTable("CertificateAwards");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.CertificateTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CertificateTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DEFAULT_WORKSHOP",
                            Description = "Potvrda o uspešno završenoj radionici.",
                            Title = "Diploma"
                        });
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ChildProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ChildProfiles");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LessonId");

                    b.HasIndex("MediaAssetId");

                    b.ToTable("ContentBlocks", t =>
                        {
                            t.HasCheckConstraint("CK_ContentBlocks_OneOwner", "(\"LessonId\" IS NOT NULL AND \"ExerciseId\" IS NULL) OR (\"LessonId\" IS NULL AND \"ExerciseId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.HasIndex("ChildProfileId", "WorkshopId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrintable")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "System administrator with full access to all features.",
                            RoleName = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mentor who guides and supports children on the platform.",
                            RoleName = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Child user of the platform.",
                            RoleName = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Parent who manages their children's profiles and activities.",
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("AgeMax")
                        .HasColumnType("integer");

                    b.Property<int>("AgeMin")
                        .HasColumnType("integer");

                    b.Property<int>("ComplexityLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("WorkshopExercises", b =>
                {
                    b.Property<int>("ExercisesId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopsId")
                        .HasColumnType("integer");

                    b.HasKey("ExercisesId", "WorkshopsId");

                    b.HasIndex("WorkshopsId");

                    b.ToTable("WorkshopExercises");
                });

            modelBuilder.Entity("WorkshopLessons", b =>
                {
                    b.Property<int>("LessonsId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopsId")
                        .HasColumnType("integer");

                    b.HasKey("LessonsId", "WorkshopsId");

                    b.HasIndex("WorkshopsId");

                    b.ToTable("WorkshopLessons");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ActivityProgress", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("ActivityProgresses")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.BadgeAward", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.BadgeTemplate", "BadgeTemplate")
                        .WithMany("Awards")
                        .HasForeignKey("BadgeTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.ChildProfile", "ChildProfile")
                        .WithMany("BadgeAwards")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("BadgeAwards")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KorakPoKorak.Domain.Entities.Workshop", "Workshop")
                        .WithMany("BadgeAwards")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BadgeTemplate");

                    b.Navigation("ChildProfile");

                    b.Navigation("Enrollment");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.CertificateAward", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.CertificateTemplate", "CertificateTemplate")
                        .WithMany("Awards")
                        .HasForeignKey("CertificateTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.ChildProfile", "ChildProfile")
                        .WithMany("CertificateAwards")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.Enrollment", "Enrollment")
                        .WithOne("CertificateAward")
                        .HasForeignKey("KorakPoKorak.Domain.Entities.CertificateAward", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.Workshop", "Workshop")
                        .WithMany("CertificateAwards")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CertificateTemplate");

                    b.Navigation("ChildProfile");

                    b.Navigation("Enrollment");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ChildProfile", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ContentBlock", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Exercise", "Exercise")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorakPoKorak.Domain.Entities.Lesson", "Lesson")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KorakPoKorak.Domain.Entities.MediaAsset", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Lesson");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Enrollments")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.Workshop", "Workshop")
                        .WithMany("Enrollments")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.User", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Workshop", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("WorkshopExercises", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.Workshop", null)
                        .WithMany()
                        .HasForeignKey("WorkshopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkshopLessons", b =>
                {
                    b.HasOne("KorakPoKorak.Domain.Entities.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KorakPoKorak.Domain.Entities.Workshop", null)
                        .WithMany()
                        .HasForeignKey("WorkshopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.BadgeTemplate", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.CertificateTemplate", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.ChildProfile", b =>
                {
                    b.Navigation("BadgeAwards");

                    b.Navigation("CertificateAwards");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Enrollment", b =>
                {
                    b.Navigation("ActivityProgresses");

                    b.Navigation("BadgeAwards");

                    b.Navigation("CertificateAward");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KorakPoKorak.Domain.Entities.Workshop", b =>
                {
                    b.Navigation("BadgeAwards");

                    b.Navigation("CertificateAwards");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
